version: '3'

services:
  website:
    restart: always
    build: .
    environment:
      - VIRTUAL_HOST=yadunut.com
      - LETSENCRYPT_HOST=yadunut.com
    networks:
      - default

networks:
  default:
    external:
      name: nginx_default
